[build]
  command = "npm run build"
  publish = "dist"

  # Default build command.
  command = "echo 'default context'"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"